version: '3'
services:
  streamer:
    build: ./streamer
    ports:
      - "80:80"
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./vod:/videos
  seed:
    build: ./seed
    depends_on:
      - "streamer"
    devices:
      - "/dev/video0:/dev/video0"
